"""
Public Widget Subrouter

Public endpoints for storefront widget delivery via HMAC-signed URLs.
Used by non-Shopify platforms (WooCommerce, Magento, custom sites).

Storefront URL pattern (generated by WordPress plugin / JS snippet):
    https://server.nudgio.tech/ecommerce/widget/{type}?key_id=5&ts=1709913600&nonce=a1b2c3&top=4&style=card&sig=<HMAC>

Security:
- HMAC-SHA256 signature covers ALL query params (prevents tampering)
- Timestamp + nonce prevent replay attacks
- Domain restriction as secondary signal (defense-in-depth)
- Dedicated rate limiting (per key_id + per IP)

Endpoints:
- GET /widget/bestsellers — bestseller widget HTML
- GET /widget/cross-sell — cross-sell widget HTML (requires product_id)
- GET /widget/upsell — upsell widget HTML (requires product_id)
- GET /widget/similar — similar products widget HTML (requires product_id)

Auth: HMAC-signed URLs (NOT JWT, NOT raw API key in query string).
All responses are HTMLResponse (renders inside iframe on merchant's storefront).
"""

import logging

from fastapi import APIRouter, Depends, Query, Request
from fastapi.responses import HTMLResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from core.db import get_session
from ..models import RecommendationSettings
from ..schemas.recommendation_schemas import BestsellerMethod
from ..adapters.factory import get_adapter
from ..engine.engine import RecommendationEngine
from ..utils.cache_utils import (
    get_cached_recommendations, set_cached_recommendations,
    get_cached_service_status, set_cached_service_status,
    get_cached_settings, set_cached_settings,
)
from ..utils.subscription_utils import is_service_active
from ..utils.widget_auth_utils import (
    verify_widget_signature,
    check_domain_restriction,
    check_widget_rate_limit,
    WidgetAuthError,
)
from .components_subrouter import generate_recommendation_html, get_default_shop_urls, apply_visual_defaults

logger = logging.getLogger(__name__)

# ==========================================
# Public Widget Router
# ==========================================

router = APIRouter(prefix="/widget", tags=["Public Widget"])


# ==========================================
# Error HTML Templates
# ==========================================

def _error_html(message: str) -> str:
    """Generate minimal error HTML for iframe display."""
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="display:flex;align-items:center;justify-content:center;min-height:100px;font-family:sans-serif;color:#6B7280;">
    <p>{message}</p>
</body>
</html>"""


# ==========================================
# Settings Cache Helpers
# ==========================================

# Fields from RecommendationSettings to cache for visual/URL rendering
_SETTINGS_CACHE_FIELDS = [
    "shop_base_url", "product_url_template",
    # Group 1: Widget Container
    "widget_bg_color", "widget_padding",
    # Group 2: Widget Title
    "widget_title", "title_color", "title_size", "title_alignment",
    # Group 3: Layout
    "widget_style", "widget_columns", "gap", "card_min_width", "card_max_width",
    # Group 4: Product Card
    "card_bg_color", "card_border_radius", "card_border_width", "card_border_color",
    "card_shadow", "card_padding", "card_hover",
    # Group 5: Product Image
    "image_aspect_w", "image_aspect_h", "image_fit", "image_radius",
    # Group 6: Product Title in Card
    "product_title_color", "product_title_size", "product_title_weight",
    "product_title_lines", "product_title_alignment",
    # Group 7: Price
    "show_price", "price_color", "price_size",
    # Group 8: CTA Button
    "button_text", "button_bg_color", "button_text_color",
    "button_radius", "button_size", "button_variant", "button_full_width",
]


def _settings_to_dict(rec_settings) -> dict | None:
    """Extract cacheable fields from RecommendationSettings ORM object."""
    if rec_settings is None:
        return None
    return {f: getattr(rec_settings, f, None) for f in _SETTINGS_CACHE_FIELDS}


def _settings_from_cache(cached_dict: dict):
    """
    Reconstruct a settings-like object from cached dict.
    Uses SimpleNamespace so getattr() works in apply_visual_defaults() and
    get_default_shop_urls().
    Returns None if cached_dict is the empty sentinel.
    """
    from types import SimpleNamespace
    if cached_dict.get("_empty"):
        return None
    return SimpleNamespace(**cached_dict)


# ==========================================
# Shared Auth + Rate Limit Flow
# ==========================================

async def _authenticate_widget_request(
    request: Request, db: AsyncSession
) -> tuple:
    """
    Common authentication flow for all widget endpoints.

    This function:
    1. Verify HMAC signature via verify_widget_signature
    2. Check domain restriction (secondary signal)
    3. Check dedicated rate limit (per key_id + per IP)
    4. Check entitlement via is_service_active
    5. Return (api_key, connection)

    Raises:
        WidgetAuthError on auth failure
        Returns HTMLResponse tuple (content, status_code) on non-auth failure
    """
    # Step 1: Verify HMAC signature
    api_key, connection = await verify_widget_signature(dict(request.query_params), db)

    # Step 2: Check domain restriction (secondary signal — defense-in-depth)
    referer = request.headers.get("referer")
    if not check_domain_restriction(api_key, referer):
        logger.warning(f"Widget: domain restriction failed for key_id={api_key.id}, referer={referer}")
        raise WidgetAuthError("Domain not allowed")

    # Step 3: Check dedicated rate limit
    client_ip = request.client.host if request.client else "unknown"
    rate_ok = await check_widget_rate_limit(api_key.id, client_ip)
    if not rate_ok:
        raise WidgetAuthError("Rate limit exceeded")

    # Step 4: Check entitlement (cached — avoids subscription DB query on every render)
    cached_status = await get_cached_service_status(connection.organization_id)
    if cached_status is not None:
        service_active = cached_status
    else:
        service_active = await is_service_active(connection.organization_id, db)
        await set_cached_service_status(connection.organization_id, service_active)
    if not service_active:
        logger.info(f"Widget: service inactive for key_id={api_key.id}, org_id={connection.organization_id}")
        raise WidgetAuthError("Widget unavailable — subscription required")

    return api_key, connection


# ==========================================
# GET /bestsellers — Bestseller Widget
# ==========================================

@router.get("/bestsellers", response_class=HTMLResponse)
async def get_bestsellers_widget(
    request: Request,
    key_id: int = Query(..., description="Widget API key ID (public identifier)"),
    ts: int = Query(..., description="Unix timestamp (request time)"),
    nonce: str = Query(..., description="Random string per request (prevents replay)"),
    sig: str = Query(..., description="HMAC-SHA256 signature of canonical query string"),
    top: int = Query(4, description="Number of recommendations to show"),
    lookback_days: int = Query(30, description="Number of days to look back for order data"),
    method: str = Query("volume", description="Bestseller calculation method: volume, value, or balanced"),
    device: str = Query("desktop", description="Target device: desktop, mobile"),
    # Group 1: Widget Container
    widget_bg_color: str = Query("#FFFFFF", description="Widget background color hex"),
    widget_padding: int = Query(16, description="Widget padding in pixels"),
    # Group 2: Widget Title
    widget_title: str = Query("", description="Custom widget title (empty = auto-default based on type)"),
    title_color: str = Query("#111827", description="Widget title color hex"),
    title_size: int = Query(24, description="Widget title font-size in pixels"),
    title_alignment: str = Query("left", description="Widget title alignment: left, center"),
    # Group 3: Layout
    widget_style: str = Query("grid", description="Widget layout style: grid, carousel"),
    widget_columns: int = Query(4, description="Max grid columns at full width (2-6)"),
    gap: int = Query(16, description="Gap between cards in pixels"),
    card_min_width: int = Query(200, description="Min card width in pixels"),
    card_max_width: int = Query(0, description="Max card width in pixels (0 = no limit)"),
    # Group 4: Product Card
    card_bg_color: str = Query("#FFFFFF", description="Card background color hex"),
    card_border_radius: int = Query(8, description="Card border radius in pixels"),
    card_border_width: int = Query(1, description="Card border width in pixels"),
    card_border_color: str = Query("#E5E7EB", description="Card border color hex"),
    card_shadow: str = Query("sm", description="Card shadow: none, sm, md, lg"),
    card_padding: int = Query(16, description="Card content padding in pixels"),
    card_hover: str = Query("lift", description="Card hover effect: none, lift, shadow, glow"),
    # Group 5: Product Image
    image_aspect_w: int = Query(1, description="Image aspect ratio width (e.g. 1, 3, 4, 16)"),
    image_aspect_h: int = Query(1, description="Image aspect ratio height (e.g. 1, 4, 5, 9)"),
    image_fit: str = Query("cover", description="Image object-fit: cover, contain"),
    image_radius: int = Query(8, description="Image border radius in pixels"),
    # Group 6: Product Title in Card
    product_title_color: str = Query("#1F2937", description="Product title color hex"),
    product_title_size: int = Query(14, description="Product title font-size in pixels"),
    product_title_weight: int = Query(500, description="CSS font-weight (100-900)"),
    product_title_lines: int = Query(2, description="Product title max lines before truncation (1-3)"),
    product_title_alignment: str = Query("left", description="Product title alignment: left, center"),
    # Group 7: Price
    show_price: bool = Query(True, description="Show product price"),
    price_color: str = Query("#111827", description="Price text color hex"),
    price_size: int = Query(18, description="Price font-size in pixels"),
    # Group 8: CTA Button
    button_text: str = Query("View", description="CTA button text"),
    button_bg_color: str = Query("#3B82F6", description="Button background color hex"),
    button_text_color: str = Query("#FFFFFF", description="Button text color hex"),
    button_radius: int = Query(6, description="Button border radius in pixels"),
    button_size: int = Query(14, description="Button font-size in pixels"),
    button_variant: str = Query("solid", description="Button style variant: solid, outline, ghost"),
    button_full_width: bool = Query(False, description="Button stretches to full card width"),
    db: AsyncSession = Depends(get_session),
):
    """
    Serve bestseller recommendation widget HTML via HMAC-signed URL.

    Public endpoint — no JWT, no session token. Authenticated via HMAC
    signature covering all query parameters.

    This endpoint:
    1. Authenticate request (HMAC + domain + rate limit + entitlement)
    2. Get RecommendationSettings for shop URL configuration
    3. Create adapter + engine, check cache or generate bestseller recommendations
    4. Generate HTML widget via generate_recommendation_html
    5. Return HTMLResponse for iframe rendering
    """
    try:
        # Step 1: Authenticate
        api_key, connection = await _authenticate_widget_request(request, db)

        # Step 2: Get shop URL settings (cached — avoids settings DB query on every render)
        cached_settings = await get_cached_settings(connection.id)
        if cached_settings is not None:
            rec_settings = _settings_from_cache(cached_settings)
        else:
            settings_result = await db.execute(
                select(RecommendationSettings).where(
                    RecommendationSettings.connection_id == connection.id
                )
            )
            rec_settings = settings_result.scalar_one_or_none()
            await set_cached_settings(connection.id, _settings_to_dict(rec_settings))
        shop_urls = get_default_shop_urls(connection, rec_settings)

        # Apply visual defaults fallback chain: URL param → DB brand defaults → hardcoded
        vis = apply_visual_defaults(
            rec_settings,
            # Group 1: Widget Container
            widget_bg_color=widget_bg_color, widget_padding=widget_padding,
            # Group 2: Widget Title
            widget_title=widget_title, title_color=title_color, title_size=title_size,
            title_alignment=title_alignment,
            # Group 3: Layout
            widget_style=widget_style, widget_columns=widget_columns, gap=gap,
            card_min_width=card_min_width, card_max_width=card_max_width,
            # Group 4: Product Card
            card_bg_color=card_bg_color, card_border_radius=card_border_radius,
            card_border_width=card_border_width, card_border_color=card_border_color,
            card_shadow=card_shadow, card_padding=card_padding, card_hover=card_hover,
            # Group 5: Product Image
            image_aspect_w=image_aspect_w, image_aspect_h=image_aspect_h, image_fit=image_fit, image_radius=image_radius,
            # Group 6: Product Title in Card
            product_title_color=product_title_color, product_title_size=product_title_size,
            product_title_weight=product_title_weight, product_title_lines=product_title_lines,
            product_title_alignment=product_title_alignment,
            # Group 7: Price
            show_price=show_price, price_color=price_color, price_size=price_size,
            # Group 8: CTA Button
            button_text=button_text, button_bg_color=button_bg_color,
            button_text_color=button_text_color, button_radius=button_radius,
            button_size=button_size, button_variant=button_variant,
            button_full_width=button_full_width,
        )

        # Step 3: Create adapter + engine, check cache or generate
        adapter = get_adapter(connection, db)
        engine = RecommendationEngine(adapter)

        cached = await get_cached_recommendations(
            connection.id, "bestseller",
            limit=top, method=method, lookback_days=lookback_days,
        )
        if cached is not None:
            recs = cached
        else:
            method_enum = BestsellerMethod(method) if method in [m.value for m in BestsellerMethod] else BestsellerMethod.VOLUME
            recs = await engine.get_bestsellers(limit=top, lookback_days=lookback_days, method=method_enum)
            await set_cached_recommendations(
                connection.id, "bestseller", recs,
                limit=top, method=method, lookback_days=lookback_days,
            )

        # Step 4: Generate HTML widget
        html = generate_recommendation_html(
            recommendations=recs, vis=vis,
            rec_type="bestseller", shop_urls=shop_urls,
        )

        # Step 5: Return HTMLResponse
        return HTMLResponse(content=html)

    except WidgetAuthError as e:
        logger.warning(f"Widget bestsellers auth error: {str(e)}")
        status_code = 429 if "rate limit" in str(e).lower() else 403
        return HTMLResponse(content=_error_html(str(e)), status_code=status_code)
    except Exception as e:
        logger.error(f"Widget bestsellers error: {str(e)}")
        return HTMLResponse(content=_error_html("Error loading recommendations"), status_code=500)


# ==========================================
# GET /cross-sell — Cross-Sell Widget
# ==========================================

@router.get("/cross-sell", response_class=HTMLResponse)
async def get_cross_sell_widget(
    request: Request,
    key_id: int = Query(..., description="Widget API key ID (public identifier)"),
    ts: int = Query(..., description="Unix timestamp (request time)"),
    nonce: str = Query(..., description="Random string per request (prevents replay)"),
    sig: str = Query(..., description="HMAC-SHA256 signature of canonical query string"),
    product_id: str | None = Query(None, description="Product ID for cross-sell recommendations (required — only works on product pages)"),
    top: int = Query(4, description="Number of recommendations to show"),
    lookback_days: int = Query(30, description="Number of days to look back for order data"),
    device: str = Query("desktop", description="Target device: desktop, mobile"),
    # Group 1: Widget Container
    widget_bg_color: str = Query("#FFFFFF", description="Widget background color hex"),
    widget_padding: int = Query(16, description="Widget padding in pixels"),
    # Group 2: Widget Title
    widget_title: str = Query("", description="Custom widget title (empty = auto-default based on type)"),
    title_color: str = Query("#111827", description="Widget title color hex"),
    title_size: int = Query(24, description="Widget title font-size in pixels"),
    title_alignment: str = Query("left", description="Widget title alignment: left, center"),
    # Group 3: Layout
    widget_style: str = Query("grid", description="Widget layout style: grid, carousel"),
    widget_columns: int = Query(4, description="Max grid columns at full width (2-6)"),
    gap: int = Query(16, description="Gap between cards in pixels"),
    card_min_width: int = Query(200, description="Min card width in pixels"),
    card_max_width: int = Query(0, description="Max card width in pixels (0 = no limit)"),
    # Group 4: Product Card
    card_bg_color: str = Query("#FFFFFF", description="Card background color hex"),
    card_border_radius: int = Query(8, description="Card border radius in pixels"),
    card_border_width: int = Query(1, description="Card border width in pixels"),
    card_border_color: str = Query("#E5E7EB", description="Card border color hex"),
    card_shadow: str = Query("sm", description="Card shadow: none, sm, md, lg"),
    card_padding: int = Query(16, description="Card content padding in pixels"),
    card_hover: str = Query("lift", description="Card hover effect: none, lift, shadow, glow"),
    # Group 5: Product Image
    image_aspect_w: int = Query(1, description="Image aspect ratio width (e.g. 1, 3, 4, 16)"),
    image_aspect_h: int = Query(1, description="Image aspect ratio height (e.g. 1, 4, 5, 9)"),
    image_fit: str = Query("cover", description="Image object-fit: cover, contain"),
    image_radius: int = Query(8, description="Image border radius in pixels"),
    # Group 6: Product Title in Card
    product_title_color: str = Query("#1F2937", description="Product title color hex"),
    product_title_size: int = Query(14, description="Product title font-size in pixels"),
    product_title_weight: int = Query(500, description="CSS font-weight (100-900)"),
    product_title_lines: int = Query(2, description="Product title max lines before truncation (1-3)"),
    product_title_alignment: str = Query("left", description="Product title alignment: left, center"),
    # Group 7: Price
    show_price: bool = Query(True, description="Show product price"),
    price_color: str = Query("#111827", description="Price text color hex"),
    price_size: int = Query(18, description="Price font-size in pixels"),
    # Group 8: CTA Button
    button_text: str = Query("View", description="CTA button text"),
    button_bg_color: str = Query("#3B82F6", description="Button background color hex"),
    button_text_color: str = Query("#FFFFFF", description="Button text color hex"),
    button_radius: int = Query(6, description="Button border radius in pixels"),
    button_size: int = Query(14, description="Button font-size in pixels"),
    button_variant: str = Query("solid", description="Button style variant: solid, outline, ghost"),
    button_full_width: bool = Query(False, description="Button stretches to full card width"),
    db: AsyncSession = Depends(get_session),
):
    """
    Serve cross-sell recommendation widget HTML via HMAC-signed URL.

    Public endpoint — no JWT, no session token. Authenticated via HMAC
    signature covering all query parameters.

    This endpoint:
    1. Check product_id is present (only available on product pages)
    2. Authenticate request (HMAC + domain + rate limit + entitlement)
    3. Get RecommendationSettings for shop URL configuration
    4. Create adapter + engine, check cache or generate cross-sell recommendations
    5. Generate HTML widget via generate_recommendation_html
    6. Return HTMLResponse for iframe rendering
    """
    try:
        # Step 1: product_id required — only available on product pages
        if not product_id:
            return HTMLResponse(content=_error_html("Place this widget on a product page"), status_code=200)

        # Step 2: Authenticate
        api_key, connection = await _authenticate_widget_request(request, db)

        # Step 3: Get shop URL settings (cached — avoids settings DB query on every render)
        cached_settings = await get_cached_settings(connection.id)
        if cached_settings is not None:
            rec_settings = _settings_from_cache(cached_settings)
        else:
            settings_result = await db.execute(
                select(RecommendationSettings).where(
                    RecommendationSettings.connection_id == connection.id
                )
            )
            rec_settings = settings_result.scalar_one_or_none()
            await set_cached_settings(connection.id, _settings_to_dict(rec_settings))
        shop_urls = get_default_shop_urls(connection, rec_settings)

        # Apply visual defaults fallback chain: URL param → DB brand defaults → hardcoded
        vis = apply_visual_defaults(
            rec_settings,
            # Group 1: Widget Container
            widget_bg_color=widget_bg_color, widget_padding=widget_padding,
            # Group 2: Widget Title
            widget_title=widget_title, title_color=title_color, title_size=title_size,
            title_alignment=title_alignment,
            # Group 3: Layout
            widget_style=widget_style, widget_columns=widget_columns, gap=gap,
            card_min_width=card_min_width, card_max_width=card_max_width,
            # Group 4: Product Card
            card_bg_color=card_bg_color, card_border_radius=card_border_radius,
            card_border_width=card_border_width, card_border_color=card_border_color,
            card_shadow=card_shadow, card_padding=card_padding, card_hover=card_hover,
            # Group 5: Product Image
            image_aspect_w=image_aspect_w, image_aspect_h=image_aspect_h, image_fit=image_fit, image_radius=image_radius,
            # Group 6: Product Title in Card
            product_title_color=product_title_color, product_title_size=product_title_size,
            product_title_weight=product_title_weight, product_title_lines=product_title_lines,
            product_title_alignment=product_title_alignment,
            # Group 7: Price
            show_price=show_price, price_color=price_color, price_size=price_size,
            # Group 8: CTA Button
            button_text=button_text, button_bg_color=button_bg_color,
            button_text_color=button_text_color, button_radius=button_radius,
            button_size=button_size, button_variant=button_variant,
            button_full_width=button_full_width,
        )

        # Step 4: Create adapter + engine, check cache or generate
        adapter = get_adapter(connection, db)
        engine = RecommendationEngine(adapter)

        cached = await get_cached_recommendations(
            connection.id, "cross_sell",
            product_id=product_id, limit=top, lookback_days=lookback_days,
        )
        if cached is not None:
            recs = cached
        else:
            recs = await engine.get_cross_sell(product_id=product_id, limit=top, lookback_days=lookback_days)
            await set_cached_recommendations(
                connection.id, "cross_sell", recs,
                product_id=product_id, limit=top, lookback_days=lookback_days,
            )

        # Step 5: Generate HTML widget
        html = generate_recommendation_html(
            recommendations=recs, vis=vis,
            rec_type="cross-sell", shop_urls=shop_urls,
        )

        # Step 6: Return HTMLResponse
        return HTMLResponse(content=html)

    except WidgetAuthError as e:
        logger.warning(f"Widget cross-sell auth error: {str(e)}")
        status_code = 429 if "rate limit" in str(e).lower() else 403
        return HTMLResponse(content=_error_html(str(e)), status_code=status_code)
    except Exception as e:
        logger.error(f"Widget cross-sell error: {str(e)}")
        return HTMLResponse(content=_error_html("Error loading recommendations"), status_code=500)


# ==========================================
# GET /upsell — Upsell Widget
# ==========================================

@router.get("/upsell", response_class=HTMLResponse)
async def get_upsell_widget(
    request: Request,
    key_id: int = Query(..., description="Widget API key ID (public identifier)"),
    ts: int = Query(..., description="Unix timestamp (request time)"),
    nonce: str = Query(..., description="Random string per request (prevents replay)"),
    sig: str = Query(..., description="HMAC-SHA256 signature of canonical query string"),
    product_id: str | None = Query(None, description="Product ID for upsell recommendations (required — only works on product pages)"),
    top: int = Query(4, description="Number of recommendations to show"),
    min_price_increase_percent: int = Query(10, description="Minimum price increase percentage for upsell candidates"),
    device: str = Query("desktop", description="Target device: desktop, mobile"),
    # Group 1: Widget Container
    widget_bg_color: str = Query("#FFFFFF", description="Widget background color hex"),
    widget_padding: int = Query(16, description="Widget padding in pixels"),
    # Group 2: Widget Title
    widget_title: str = Query("", description="Custom widget title (empty = auto-default based on type)"),
    title_color: str = Query("#111827", description="Widget title color hex"),
    title_size: int = Query(24, description="Widget title font-size in pixels"),
    title_alignment: str = Query("left", description="Widget title alignment: left, center"),
    # Group 3: Layout
    widget_style: str = Query("grid", description="Widget layout style: grid, carousel"),
    widget_columns: int = Query(4, description="Max grid columns at full width (2-6)"),
    gap: int = Query(16, description="Gap between cards in pixels"),
    card_min_width: int = Query(200, description="Min card width in pixels"),
    card_max_width: int = Query(0, description="Max card width in pixels (0 = no limit)"),
    # Group 4: Product Card
    card_bg_color: str = Query("#FFFFFF", description="Card background color hex"),
    card_border_radius: int = Query(8, description="Card border radius in pixels"),
    card_border_width: int = Query(1, description="Card border width in pixels"),
    card_border_color: str = Query("#E5E7EB", description="Card border color hex"),
    card_shadow: str = Query("sm", description="Card shadow: none, sm, md, lg"),
    card_padding: int = Query(16, description="Card content padding in pixels"),
    card_hover: str = Query("lift", description="Card hover effect: none, lift, shadow, glow"),
    # Group 5: Product Image
    image_aspect_w: int = Query(1, description="Image aspect ratio width (e.g. 1, 3, 4, 16)"),
    image_aspect_h: int = Query(1, description="Image aspect ratio height (e.g. 1, 4, 5, 9)"),
    image_fit: str = Query("cover", description="Image object-fit: cover, contain"),
    image_radius: int = Query(8, description="Image border radius in pixels"),
    # Group 6: Product Title in Card
    product_title_color: str = Query("#1F2937", description="Product title color hex"),
    product_title_size: int = Query(14, description="Product title font-size in pixels"),
    product_title_weight: int = Query(500, description="CSS font-weight (100-900)"),
    product_title_lines: int = Query(2, description="Product title max lines before truncation (1-3)"),
    product_title_alignment: str = Query("left", description="Product title alignment: left, center"),
    # Group 7: Price
    show_price: bool = Query(True, description="Show product price"),
    price_color: str = Query("#111827", description="Price text color hex"),
    price_size: int = Query(18, description="Price font-size in pixels"),
    # Group 8: CTA Button
    button_text: str = Query("View", description="CTA button text"),
    button_bg_color: str = Query("#3B82F6", description="Button background color hex"),
    button_text_color: str = Query("#FFFFFF", description="Button text color hex"),
    button_radius: int = Query(6, description="Button border radius in pixels"),
    button_size: int = Query(14, description="Button font-size in pixels"),
    button_variant: str = Query("solid", description="Button style variant: solid, outline, ghost"),
    button_full_width: bool = Query(False, description="Button stretches to full card width"),
    db: AsyncSession = Depends(get_session),
):
    """
    Serve upsell recommendation widget HTML via HMAC-signed URL.

    Public endpoint — no JWT, no session token. Authenticated via HMAC
    signature covering all query parameters.

    This endpoint:
    1. Check product_id is present (only available on product pages)
    2. Authenticate request (HMAC + domain + rate limit + entitlement)
    3. Get RecommendationSettings for shop URL configuration
    4. Create adapter + engine, check cache or generate upsell recommendations
    5. Generate HTML widget via generate_recommendation_html
    6. Return HTMLResponse for iframe rendering
    """
    try:
        # Step 1: product_id required — only available on product pages
        if not product_id:
            return HTMLResponse(content=_error_html("Place this widget on a product page"), status_code=200)

        # Step 2: Authenticate
        api_key, connection = await _authenticate_widget_request(request, db)

        # Step 3: Get shop URL settings (cached — avoids settings DB query on every render)
        cached_settings = await get_cached_settings(connection.id)
        if cached_settings is not None:
            rec_settings = _settings_from_cache(cached_settings)
        else:
            settings_result = await db.execute(
                select(RecommendationSettings).where(
                    RecommendationSettings.connection_id == connection.id
                )
            )
            rec_settings = settings_result.scalar_one_or_none()
            await set_cached_settings(connection.id, _settings_to_dict(rec_settings))
        shop_urls = get_default_shop_urls(connection, rec_settings)

        # Apply visual defaults fallback chain: URL param → DB brand defaults → hardcoded
        vis = apply_visual_defaults(
            rec_settings,
            # Group 1: Widget Container
            widget_bg_color=widget_bg_color, widget_padding=widget_padding,
            # Group 2: Widget Title
            widget_title=widget_title, title_color=title_color, title_size=title_size,
            title_alignment=title_alignment,
            # Group 3: Layout
            widget_style=widget_style, widget_columns=widget_columns, gap=gap,
            card_min_width=card_min_width, card_max_width=card_max_width,
            # Group 4: Product Card
            card_bg_color=card_bg_color, card_border_radius=card_border_radius,
            card_border_width=card_border_width, card_border_color=card_border_color,
            card_shadow=card_shadow, card_padding=card_padding, card_hover=card_hover,
            # Group 5: Product Image
            image_aspect_w=image_aspect_w, image_aspect_h=image_aspect_h, image_fit=image_fit, image_radius=image_radius,
            # Group 6: Product Title in Card
            product_title_color=product_title_color, product_title_size=product_title_size,
            product_title_weight=product_title_weight, product_title_lines=product_title_lines,
            product_title_alignment=product_title_alignment,
            # Group 7: Price
            show_price=show_price, price_color=price_color, price_size=price_size,
            # Group 8: CTA Button
            button_text=button_text, button_bg_color=button_bg_color,
            button_text_color=button_text_color, button_radius=button_radius,
            button_size=button_size, button_variant=button_variant,
            button_full_width=button_full_width,
        )

        # Step 4: Create adapter + engine, check cache or generate
        adapter = get_adapter(connection, db)
        engine = RecommendationEngine(adapter)

        cached = await get_cached_recommendations(
            connection.id, "upsell",
            product_id=product_id, limit=top, min_price_increase_percent=min_price_increase_percent,
        )
        if cached is not None:
            recs = cached
        else:
            recs = await engine.get_upsell(product_id=product_id, limit=top, min_price_increase_percent=min_price_increase_percent)
            await set_cached_recommendations(
                connection.id, "upsell", recs,
                product_id=product_id, limit=top, min_price_increase_percent=min_price_increase_percent,
            )

        # Step 5: Generate HTML widget
        html = generate_recommendation_html(
            recommendations=recs, vis=vis,
            rec_type="upsell", shop_urls=shop_urls,
        )

        # Step 6: Return HTMLResponse
        return HTMLResponse(content=html)

    except WidgetAuthError as e:
        logger.warning(f"Widget upsell auth error: {str(e)}")
        status_code = 429 if "rate limit" in str(e).lower() else 403
        return HTMLResponse(content=_error_html(str(e)), status_code=status_code)
    except Exception as e:
        logger.error(f"Widget upsell error: {str(e)}")
        return HTMLResponse(content=_error_html("Error loading recommendations"), status_code=500)


# ==========================================
# GET /similar — Similar Products Widget
# ==========================================

@router.get("/similar", response_class=HTMLResponse)
async def get_similar_widget(
    request: Request,
    key_id: int = Query(..., description="Widget API key ID (public identifier)"),
    ts: int = Query(..., description="Unix timestamp (request time)"),
    nonce: str = Query(..., description="Random string per request (prevents replay)"),
    sig: str = Query(..., description="HMAC-SHA256 signature of canonical query string"),
    product_id: str | None = Query(None, description="Product ID for similar product recommendations (required — only works on product pages)"),
    top: int = Query(4, description="Number of recommendations to show"),
    device: str = Query("desktop", description="Target device: desktop, mobile"),
    # Group 1: Widget Container
    widget_bg_color: str = Query("#FFFFFF", description="Widget background color hex"),
    widget_padding: int = Query(16, description="Widget padding in pixels"),
    # Group 2: Widget Title
    widget_title: str = Query("", description="Custom widget title (empty = auto-default based on type)"),
    title_color: str = Query("#111827", description="Widget title color hex"),
    title_size: int = Query(24, description="Widget title font-size in pixels"),
    title_alignment: str = Query("left", description="Widget title alignment: left, center"),
    # Group 3: Layout
    widget_style: str = Query("grid", description="Widget layout style: grid, carousel"),
    widget_columns: int = Query(4, description="Max grid columns at full width (2-6)"),
    gap: int = Query(16, description="Gap between cards in pixels"),
    card_min_width: int = Query(200, description="Min card width in pixels"),
    card_max_width: int = Query(0, description="Max card width in pixels (0 = no limit)"),
    # Group 4: Product Card
    card_bg_color: str = Query("#FFFFFF", description="Card background color hex"),
    card_border_radius: int = Query(8, description="Card border radius in pixels"),
    card_border_width: int = Query(1, description="Card border width in pixels"),
    card_border_color: str = Query("#E5E7EB", description="Card border color hex"),
    card_shadow: str = Query("sm", description="Card shadow: none, sm, md, lg"),
    card_padding: int = Query(16, description="Card content padding in pixels"),
    card_hover: str = Query("lift", description="Card hover effect: none, lift, shadow, glow"),
    # Group 5: Product Image
    image_aspect_w: int = Query(1, description="Image aspect ratio width (e.g. 1, 3, 4, 16)"),
    image_aspect_h: int = Query(1, description="Image aspect ratio height (e.g. 1, 4, 5, 9)"),
    image_fit: str = Query("cover", description="Image object-fit: cover, contain"),
    image_radius: int = Query(8, description="Image border radius in pixels"),
    # Group 6: Product Title in Card
    product_title_color: str = Query("#1F2937", description="Product title color hex"),
    product_title_size: int = Query(14, description="Product title font-size in pixels"),
    product_title_weight: int = Query(500, description="CSS font-weight (100-900)"),
    product_title_lines: int = Query(2, description="Product title max lines before truncation (1-3)"),
    product_title_alignment: str = Query("left", description="Product title alignment: left, center"),
    # Group 7: Price
    show_price: bool = Query(True, description="Show product price"),
    price_color: str = Query("#111827", description="Price text color hex"),
    price_size: int = Query(18, description="Price font-size in pixels"),
    # Group 8: CTA Button
    button_text: str = Query("View", description="CTA button text"),
    button_bg_color: str = Query("#3B82F6", description="Button background color hex"),
    button_text_color: str = Query("#FFFFFF", description="Button text color hex"),
    button_radius: int = Query(6, description="Button border radius in pixels"),
    button_size: int = Query(14, description="Button font-size in pixels"),
    button_variant: str = Query("solid", description="Button style variant: solid, outline, ghost"),
    button_full_width: bool = Query(False, description="Button stretches to full card width"),
    db: AsyncSession = Depends(get_session),
):
    """
    Serve similar products recommendation widget HTML via HMAC-signed URL.

    Public endpoint — no JWT, no session token. Authenticated via HMAC
    signature covering all query parameters.

    This endpoint:
    1. Check product_id is present (only available on product pages)
    2. Authenticate request (HMAC + domain + rate limit + entitlement)
    3. Get RecommendationSettings for shop URL configuration
    4. Create adapter + engine, check cache or generate similar product recommendations
    5. Generate HTML widget via generate_recommendation_html
    6. Return HTMLResponse for iframe rendering
    """
    try:
        # Step 1: product_id required — only available on product pages
        if not product_id:
            return HTMLResponse(content=_error_html("Place this widget on a product page"), status_code=200)

        # Step 2: Authenticate
        api_key, connection = await _authenticate_widget_request(request, db)

        # Step 3: Get shop URL settings (cached — avoids settings DB query on every render)
        cached_settings = await get_cached_settings(connection.id)
        if cached_settings is not None:
            rec_settings = _settings_from_cache(cached_settings)
        else:
            settings_result = await db.execute(
                select(RecommendationSettings).where(
                    RecommendationSettings.connection_id == connection.id
                )
            )
            rec_settings = settings_result.scalar_one_or_none()
            await set_cached_settings(connection.id, _settings_to_dict(rec_settings))
        shop_urls = get_default_shop_urls(connection, rec_settings)

        # Apply visual defaults fallback chain: URL param → DB brand defaults → hardcoded
        vis = apply_visual_defaults(
            rec_settings,
            # Group 1: Widget Container
            widget_bg_color=widget_bg_color, widget_padding=widget_padding,
            # Group 2: Widget Title
            widget_title=widget_title, title_color=title_color, title_size=title_size,
            title_alignment=title_alignment,
            # Group 3: Layout
            widget_style=widget_style, widget_columns=widget_columns, gap=gap,
            card_min_width=card_min_width, card_max_width=card_max_width,
            # Group 4: Product Card
            card_bg_color=card_bg_color, card_border_radius=card_border_radius,
            card_border_width=card_border_width, card_border_color=card_border_color,
            card_shadow=card_shadow, card_padding=card_padding, card_hover=card_hover,
            # Group 5: Product Image
            image_aspect_w=image_aspect_w, image_aspect_h=image_aspect_h, image_fit=image_fit, image_radius=image_radius,
            # Group 6: Product Title in Card
            product_title_color=product_title_color, product_title_size=product_title_size,
            product_title_weight=product_title_weight, product_title_lines=product_title_lines,
            product_title_alignment=product_title_alignment,
            # Group 7: Price
            show_price=show_price, price_color=price_color, price_size=price_size,
            # Group 8: CTA Button
            button_text=button_text, button_bg_color=button_bg_color,
            button_text_color=button_text_color, button_radius=button_radius,
            button_size=button_size, button_variant=button_variant,
            button_full_width=button_full_width,
        )

        # Step 4: Create adapter + engine, check cache or generate
        adapter = get_adapter(connection, db)
        engine = RecommendationEngine(adapter)

        cached = await get_cached_recommendations(
            connection.id, "similar",
            product_id=product_id, limit=top,
        )
        if cached is not None:
            recs = cached
        else:
            recs = await engine.get_similar(product_id=product_id, limit=top)
            await set_cached_recommendations(
                connection.id, "similar", recs,
                product_id=product_id, limit=top,
            )

        # Step 5: Generate HTML widget
        html = generate_recommendation_html(
            recommendations=recs, vis=vis,
            rec_type="similar", shop_urls=shop_urls,
        )

        # Step 6: Return HTMLResponse
        return HTMLResponse(content=html)

    except WidgetAuthError as e:
        logger.warning(f"Widget similar auth error: {str(e)}")
        status_code = 429 if "rate limit" in str(e).lower() else 403
        return HTMLResponse(content=_error_html(str(e)), status_code=status_code)
    except Exception as e:
        logger.error(f"Widget similar error: {str(e)}")
        return HTMLResponse(content=_error_html("Error loading recommendations"), status_code=500)
