"""
Public Widget Subrouter

Public endpoints for storefront widget delivery via HMAC-signed URLs.
Used by non-Shopify platforms (WooCommerce, Magento, custom sites).

Storefront URL pattern (generated by WordPress plugin / JS snippet):
    https://server.nudgio.tech/ecommerce/widget/{type}?key_id=5&ts=1709913600&nonce=a1b2c3&top=4&style=card&sig=<HMAC>

Security:
- HMAC-SHA256 signature covers ALL query params (prevents tampering)
- Timestamp + nonce prevent replay attacks
- Domain restriction as secondary signal (defense-in-depth)
- Dedicated rate limiting (per key_id + per IP)

Endpoints:
- GET /widget/bestsellers — bestseller widget HTML
- GET /widget/cross-sell — cross-sell widget HTML (requires product_id)
- GET /widget/upsell — upsell widget HTML (requires product_id)
- GET /widget/similar — similar products widget HTML (requires product_id)

Auth: HMAC-signed URLs (NOT JWT, NOT raw API key in query string).
All responses are HTMLResponse (renders inside iframe on merchant's storefront).
"""

import logging

from fastapi import APIRouter, Depends, Query, Request
from fastapi.responses import HTMLResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from core.db import get_session
from ..models import RecommendationSettings
from ..schemas.recommendation_schemas import BestsellerMethod
from ..adapters.factory import get_adapter
from ..engine.engine import RecommendationEngine
from ..utils.cache_utils import get_cached_recommendations, set_cached_recommendations
from ..utils.subscription_utils import is_service_active
from ..utils.widget_auth_utils import (
    verify_widget_signature,
    check_domain_restriction,
    check_widget_rate_limit,
    WidgetAuthError,
)
from .components_subrouter import generate_recommendation_html, get_default_shop_urls

logger = logging.getLogger(__name__)

# ==========================================
# Public Widget Router
# ==========================================

router = APIRouter(prefix="/widget", tags=["Public Widget"])


# ==========================================
# Error HTML Templates
# ==========================================

def _error_html(message: str) -> str:
    """Generate minimal error HTML for iframe display."""
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="display:flex;align-items:center;justify-content:center;min-height:100px;font-family:sans-serif;color:#6B7280;">
    <p>{message}</p>
</body>
</html>"""


# ==========================================
# Shared Auth + Rate Limit Flow
# ==========================================

async def _authenticate_widget_request(
    request: Request, db: AsyncSession
) -> tuple:
    """
    Common authentication flow for all widget endpoints.

    This function:
    1. Verify HMAC signature via verify_widget_signature
    2. Check domain restriction (secondary signal)
    3. Check dedicated rate limit (per key_id + per IP)
    4. Check entitlement via is_service_active
    5. Return (api_key, connection)

    Raises:
        WidgetAuthError on auth failure
        Returns HTMLResponse tuple (content, status_code) on non-auth failure
    """
    # Step 1: Verify HMAC signature
    api_key, connection = await verify_widget_signature(dict(request.query_params), db)

    # Step 2: Check domain restriction (secondary signal — defense-in-depth)
    referer = request.headers.get("referer")
    if not check_domain_restriction(api_key, referer):
        logger.warning(f"Widget: domain restriction failed for key_id={api_key.id}, referer={referer}")
        raise WidgetAuthError("Domain not allowed")

    # Step 3: Check dedicated rate limit
    client_ip = request.client.host if request.client else "unknown"
    rate_ok = await check_widget_rate_limit(api_key.id, client_ip)
    if not rate_ok:
        raise WidgetAuthError("Rate limit exceeded")

    # Step 4: Check entitlement (active subscription or free tier)
    service_active = await is_service_active(connection.organization_id, db)
    if not service_active:
        logger.info(f"Widget: service inactive for key_id={api_key.id}, org_id={connection.organization_id}")
        raise WidgetAuthError("Widget unavailable — subscription required")

    return api_key, connection


# ==========================================
# GET /bestsellers — Bestseller Widget
# ==========================================

@router.get("/bestsellers", response_class=HTMLResponse)
async def get_bestsellers_widget(
    request: Request,
    key_id: int = Query(..., description="Widget API key ID (public identifier)"),
    ts: int = Query(..., description="Unix timestamp (request time)"),
    nonce: str = Query(..., description="Random string per request (prevents replay)"),
    sig: str = Query(..., description="HMAC-SHA256 signature of canonical query string"),
    top: int = Query(4, description="Number of recommendations to show"),
    lookback_days: int = Query(30, description="Number of days to look back for order data"),
    method: str = Query("volume", description="Bestseller calculation method: volume, value, or balanced"),
    style: str = Query("card", description="Component style: card, carousel"),
    device: str = Query("desktop", description="Target device: desktop, mobile"),
    columns: int = Query(4, description="Max columns at full width (2–6)"),
    size: str = Query("default", description="Visual density: compact, default, spacious"),
    primary_color: str = Query("#3B82F6", description="Primary color hex"),
    text_color: str = Query("#1F2937", description="Text color hex"),
    bg_color: str = Query("#FFFFFF", description="Background color hex"),
    border_radius: str = Query("8px", description="Border radius"),
    db: AsyncSession = Depends(get_session),
):
    """
    Serve bestseller recommendation widget HTML via HMAC-signed URL.

    Public endpoint — no JWT, no session token. Authenticated via HMAC
    signature covering all query parameters.

    This endpoint:
    1. Authenticate request (HMAC + domain + rate limit + entitlement)
    2. Get RecommendationSettings for shop URL configuration
    3. Create adapter + engine, check cache or generate bestseller recommendations
    4. Generate HTML widget via generate_recommendation_html
    5. Return HTMLResponse for iframe rendering
    """
    try:
        # Step 1: Authenticate
        api_key, connection = await _authenticate_widget_request(request, db)

        # Step 2: Get shop URL settings
        settings_result = await db.execute(
            select(RecommendationSettings).where(
                RecommendationSettings.connection_id == connection.id
            )
        )
        rec_settings = settings_result.scalar_one_or_none()
        shop_urls = get_default_shop_urls(connection, rec_settings)

        # Step 3: Create adapter + engine, check cache or generate
        adapter = get_adapter(connection, db)
        engine = RecommendationEngine(adapter)

        cached = await get_cached_recommendations(
            connection.id, "bestseller",
            limit=top, method=method, lookback_days=lookback_days,
        )
        if cached is not None:
            recs = cached
        else:
            method_enum = BestsellerMethod(method) if method in [m.value for m in BestsellerMethod] else BestsellerMethod.VOLUME
            recs = await engine.get_bestsellers(limit=top, lookback_days=lookback_days, method=method_enum)
            await set_cached_recommendations(
                connection.id, "bestseller", recs,
                limit=top, method=method, lookback_days=lookback_days,
            )

        # Step 4: Generate HTML widget
        html = generate_recommendation_html(
            recommendations=recs,
            style=style,
            device=device,
            columns=columns,
            size=size,
            colors={"primary": primary_color, "text": text_color, "bg": bg_color},
            border_radius=border_radius,
            rec_type="bestseller",
            shop_urls=shop_urls,
        )

        # Step 5: Return HTMLResponse
        return HTMLResponse(content=html)

    except WidgetAuthError as e:
        logger.warning(f"Widget bestsellers auth error: {str(e)}")
        status_code = 429 if "rate limit" in str(e).lower() else 403
        return HTMLResponse(content=_error_html(str(e)), status_code=status_code)
    except Exception as e:
        logger.error(f"Widget bestsellers error: {str(e)}")
        return HTMLResponse(content=_error_html("Error loading recommendations"), status_code=500)


# ==========================================
# GET /cross-sell — Cross-Sell Widget
# ==========================================

@router.get("/cross-sell", response_class=HTMLResponse)
async def get_cross_sell_widget(
    request: Request,
    key_id: int = Query(..., description="Widget API key ID (public identifier)"),
    ts: int = Query(..., description="Unix timestamp (request time)"),
    nonce: str = Query(..., description="Random string per request (prevents replay)"),
    sig: str = Query(..., description="HMAC-SHA256 signature of canonical query string"),
    product_id: str | None = Query(None, description="Product ID for cross-sell recommendations (required — only works on product pages)"),
    top: int = Query(4, description="Number of recommendations to show"),
    lookback_days: int = Query(30, description="Number of days to look back for order data"),
    style: str = Query("card", description="Component style: card, carousel"),
    device: str = Query("desktop", description="Target device: desktop, mobile"),
    columns: int = Query(4, description="Max columns at full width (2–6)"),
    size: str = Query("default", description="Visual density: compact, default, spacious"),
    primary_color: str = Query("#3B82F6", description="Primary color hex"),
    text_color: str = Query("#1F2937", description="Text color hex"),
    bg_color: str = Query("#FFFFFF", description="Background color hex"),
    border_radius: str = Query("8px", description="Border radius"),
    db: AsyncSession = Depends(get_session),
):
    """
    Serve cross-sell recommendation widget HTML via HMAC-signed URL.

    Public endpoint — no JWT, no session token. Authenticated via HMAC
    signature covering all query parameters.

    This endpoint:
    1. Check product_id is present (only available on product pages)
    2. Authenticate request (HMAC + domain + rate limit + entitlement)
    3. Get RecommendationSettings for shop URL configuration
    4. Create adapter + engine, check cache or generate cross-sell recommendations
    5. Generate HTML widget via generate_recommendation_html
    6. Return HTMLResponse for iframe rendering
    """
    try:
        # Step 1: product_id required — only available on product pages
        if not product_id:
            return HTMLResponse(content=_error_html("Place this widget on a product page"), status_code=200)

        # Step 2: Authenticate
        api_key, connection = await _authenticate_widget_request(request, db)

        # Step 3: Get shop URL settings
        settings_result = await db.execute(
            select(RecommendationSettings).where(
                RecommendationSettings.connection_id == connection.id
            )
        )
        rec_settings = settings_result.scalar_one_or_none()
        shop_urls = get_default_shop_urls(connection, rec_settings)

        # Step 4: Create adapter + engine, check cache or generate
        adapter = get_adapter(connection, db)
        engine = RecommendationEngine(adapter)

        cached = await get_cached_recommendations(
            connection.id, "cross_sell",
            product_id=product_id, limit=top, lookback_days=lookback_days,
        )
        if cached is not None:
            recs = cached
        else:
            recs = await engine.get_cross_sell(product_id=product_id, limit=top, lookback_days=lookback_days)
            await set_cached_recommendations(
                connection.id, "cross_sell", recs,
                product_id=product_id, limit=top, lookback_days=lookback_days,
            )

        # Step 5: Generate HTML widget
        html = generate_recommendation_html(
            recommendations=recs,
            style=style,
            device=device,
            columns=columns,
            size=size,
            colors={"primary": primary_color, "text": text_color, "bg": bg_color},
            border_radius=border_radius,
            rec_type="cross-sell",
            shop_urls=shop_urls,
        )

        # Step 6: Return HTMLResponse
        return HTMLResponse(content=html)

    except WidgetAuthError as e:
        logger.warning(f"Widget cross-sell auth error: {str(e)}")
        status_code = 429 if "rate limit" in str(e).lower() else 403
        return HTMLResponse(content=_error_html(str(e)), status_code=status_code)
    except Exception as e:
        logger.error(f"Widget cross-sell error: {str(e)}")
        return HTMLResponse(content=_error_html("Error loading recommendations"), status_code=500)


# ==========================================
# GET /upsell — Upsell Widget
# ==========================================

@router.get("/upsell", response_class=HTMLResponse)
async def get_upsell_widget(
    request: Request,
    key_id: int = Query(..., description="Widget API key ID (public identifier)"),
    ts: int = Query(..., description="Unix timestamp (request time)"),
    nonce: str = Query(..., description="Random string per request (prevents replay)"),
    sig: str = Query(..., description="HMAC-SHA256 signature of canonical query string"),
    product_id: str | None = Query(None, description="Product ID for upsell recommendations (required — only works on product pages)"),
    top: int = Query(4, description="Number of recommendations to show"),
    min_price_increase_percent: int = Query(10, description="Minimum price increase percentage for upsell candidates"),
    style: str = Query("card", description="Component style: card, carousel"),
    device: str = Query("desktop", description="Target device: desktop, mobile"),
    columns: int = Query(4, description="Max columns at full width (2–6)"),
    size: str = Query("default", description="Visual density: compact, default, spacious"),
    primary_color: str = Query("#3B82F6", description="Primary color hex"),
    text_color: str = Query("#1F2937", description="Text color hex"),
    bg_color: str = Query("#FFFFFF", description="Background color hex"),
    border_radius: str = Query("8px", description="Border radius"),
    db: AsyncSession = Depends(get_session),
):
    """
    Serve upsell recommendation widget HTML via HMAC-signed URL.

    Public endpoint — no JWT, no session token. Authenticated via HMAC
    signature covering all query parameters.

    This endpoint:
    1. Check product_id is present (only available on product pages)
    2. Authenticate request (HMAC + domain + rate limit + entitlement)
    3. Get RecommendationSettings for shop URL configuration
    4. Create adapter + engine, check cache or generate upsell recommendations
    5. Generate HTML widget via generate_recommendation_html
    6. Return HTMLResponse for iframe rendering
    """
    try:
        # Step 1: product_id required — only available on product pages
        if not product_id:
            return HTMLResponse(content=_error_html("Place this widget on a product page"), status_code=200)

        # Step 2: Authenticate
        api_key, connection = await _authenticate_widget_request(request, db)

        # Step 3: Get shop URL settings
        settings_result = await db.execute(
            select(RecommendationSettings).where(
                RecommendationSettings.connection_id == connection.id
            )
        )
        rec_settings = settings_result.scalar_one_or_none()
        shop_urls = get_default_shop_urls(connection, rec_settings)

        # Step 4: Create adapter + engine, check cache or generate
        adapter = get_adapter(connection, db)
        engine = RecommendationEngine(adapter)

        cached = await get_cached_recommendations(
            connection.id, "upsell",
            product_id=product_id, limit=top, min_price_increase_percent=min_price_increase_percent,
        )
        if cached is not None:
            recs = cached
        else:
            recs = await engine.get_upsell(product_id=product_id, limit=top, min_price_increase_percent=min_price_increase_percent)
            await set_cached_recommendations(
                connection.id, "upsell", recs,
                product_id=product_id, limit=top, min_price_increase_percent=min_price_increase_percent,
            )

        # Step 5: Generate HTML widget
        html = generate_recommendation_html(
            recommendations=recs,
            style=style,
            device=device,
            columns=columns,
            size=size,
            colors={"primary": primary_color, "text": text_color, "bg": bg_color},
            border_radius=border_radius,
            rec_type="upsell",
            shop_urls=shop_urls,
        )

        # Step 6: Return HTMLResponse
        return HTMLResponse(content=html)

    except WidgetAuthError as e:
        logger.warning(f"Widget upsell auth error: {str(e)}")
        status_code = 429 if "rate limit" in str(e).lower() else 403
        return HTMLResponse(content=_error_html(str(e)), status_code=status_code)
    except Exception as e:
        logger.error(f"Widget upsell error: {str(e)}")
        return HTMLResponse(content=_error_html("Error loading recommendations"), status_code=500)


# ==========================================
# GET /similar — Similar Products Widget
# ==========================================

@router.get("/similar", response_class=HTMLResponse)
async def get_similar_widget(
    request: Request,
    key_id: int = Query(..., description="Widget API key ID (public identifier)"),
    ts: int = Query(..., description="Unix timestamp (request time)"),
    nonce: str = Query(..., description="Random string per request (prevents replay)"),
    sig: str = Query(..., description="HMAC-SHA256 signature of canonical query string"),
    product_id: str | None = Query(None, description="Product ID for similar product recommendations (required — only works on product pages)"),
    top: int = Query(4, description="Number of recommendations to show"),
    style: str = Query("card", description="Component style: card, carousel"),
    device: str = Query("desktop", description="Target device: desktop, mobile"),
    columns: int = Query(4, description="Max columns at full width (2–6)"),
    size: str = Query("default", description="Visual density: compact, default, spacious"),
    primary_color: str = Query("#3B82F6", description="Primary color hex"),
    text_color: str = Query("#1F2937", description="Text color hex"),
    bg_color: str = Query("#FFFFFF", description="Background color hex"),
    border_radius: str = Query("8px", description="Border radius"),
    db: AsyncSession = Depends(get_session),
):
    """
    Serve similar products recommendation widget HTML via HMAC-signed URL.

    Public endpoint — no JWT, no session token. Authenticated via HMAC
    signature covering all query parameters.

    This endpoint:
    1. Check product_id is present (only available on product pages)
    2. Authenticate request (HMAC + domain + rate limit + entitlement)
    3. Get RecommendationSettings for shop URL configuration
    4. Create adapter + engine, check cache or generate similar product recommendations
    5. Generate HTML widget via generate_recommendation_html
    6. Return HTMLResponse for iframe rendering
    """
    try:
        # Step 1: product_id required — only available on product pages
        if not product_id:
            return HTMLResponse(content=_error_html("Place this widget on a product page"), status_code=200)

        # Step 2: Authenticate
        api_key, connection = await _authenticate_widget_request(request, db)

        # Step 3: Get shop URL settings
        settings_result = await db.execute(
            select(RecommendationSettings).where(
                RecommendationSettings.connection_id == connection.id
            )
        )
        rec_settings = settings_result.scalar_one_or_none()
        shop_urls = get_default_shop_urls(connection, rec_settings)

        # Step 4: Create adapter + engine, check cache or generate
        adapter = get_adapter(connection, db)
        engine = RecommendationEngine(adapter)

        cached = await get_cached_recommendations(
            connection.id, "similar",
            product_id=product_id, limit=top,
        )
        if cached is not None:
            recs = cached
        else:
            recs = await engine.get_similar(product_id=product_id, limit=top)
            await set_cached_recommendations(
                connection.id, "similar", recs,
                product_id=product_id, limit=top,
            )

        # Step 5: Generate HTML widget
        html = generate_recommendation_html(
            recommendations=recs,
            style=style,
            device=device,
            columns=columns,
            size=size,
            colors={"primary": primary_color, "text": text_color, "bg": bg_color},
            border_radius=border_radius,
            rec_type="similar",
            shop_urls=shop_urls,
        )

        # Step 6: Return HTMLResponse
        return HTMLResponse(content=html)

    except WidgetAuthError as e:
        logger.warning(f"Widget similar auth error: {str(e)}")
        status_code = 429 if "rate limit" in str(e).lower() else 403
        return HTMLResponse(content=_error_html(str(e)), status_code=status_code)
    except Exception as e:
        logger.error(f"Widget similar error: {str(e)}")
        return HTMLResponse(content=_error_html("Error loading recommendations"), status_code=500)
