"""EcommerceConnection Sync

Revision ID: 85c33b1d507f
Revises: c81714328def
Create Date: 2026-03-08 15:39:08.824141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c33b1d507f'
down_revision: Union[str, Sequence[str], None] = 'c81714328def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecommerce_connections', sa.Column('auto_sync_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('ecommerce_connections', sa.Column('sync_interval', sa.String(length=50), server_default='daily', nullable=False))
    op.add_column('ecommerce_connections', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ecommerce_connections', sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ecommerce_connections', sa.Column('last_sync_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecommerce_connections', 'last_sync_status')
    op.drop_column('ecommerce_connections', 'next_sync_at')
    op.drop_column('ecommerce_connections', 'last_synced_at')
    op.drop_column('ecommerce_connections', 'sync_interval')
    op.drop_column('ecommerce_connections', 'auto_sync_enabled')
    # ### end Alembic commands ###
