"""Connection Method and API fields

Revision ID: 91d861a1bea9
Revises: cf04e154378b
Create Date: 2026-03-04 03:06:15.405882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91d861a1bea9'
down_revision: Union[str, Sequence[str], None] = 'cf04e154378b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('api_usage_tracking_organization_id_fkey'), 'api_usage_tracking', type_='foreignkey')
    op.drop_constraint(op.f('api_usage_tracking_connection_id_fkey'), 'api_usage_tracking', type_='foreignkey')
    op.create_foreign_key(None, 'api_usage_tracking', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'api_usage_tracking', 'ecommerce_connections', ['connection_id'], ['id'], ondelete='CASCADE')
    op.add_column('ecommerce_connections', sa.Column('connection_method', sa.String(length=50), nullable=False, server_default='api'))
    op.add_column('ecommerce_connections', sa.Column('store_url', sa.String(length=500), nullable=True))
    op.add_column('ecommerce_connections', sa.Column('api_key', sa.String(length=512), nullable=True))
    op.add_column('ecommerce_connections', sa.Column('api_secret', sa.String(length=512), nullable=True))
    op.alter_column('ecommerce_connections', 'platform',
               existing_type=postgresql.ENUM('SHOPIFY', 'WOOCOMMERCE', 'MAGENTO', name='platformtype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('ecommerce_connections', 'db_host',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ecommerce_connections', 'db_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ecommerce_connections', 'db_user',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ecommerce_connections', 'db_password',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('ecommerce_connections', 'db_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('ecommerce_connections_user_id_fkey'), 'ecommerce_connections', type_='foreignkey')
    op.drop_constraint(op.f('ecommerce_connections_organization_id_fkey'), 'ecommerce_connections', type_='foreignkey')
    op.create_foreign_key(None, 'ecommerce_connections', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ecommerce_connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recommendation_analytics', 'recommendation_type',
               existing_type=postgresql.ENUM('BESTSELLER', 'CROSS_SELL', 'UP_SELL', 'SIMILAR', 'USER_BASED', name='recommendationtype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('recommendation_analytics', 'event_type',
               existing_type=postgresql.ENUM('VIEW', 'CLICK', 'PURCHASE', name='eventtype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('recommendation_analytics_connection_id_fkey'), 'recommendation_analytics', type_='foreignkey')
    op.create_foreign_key(None, 'recommendation_analytics', 'ecommerce_connections', ['connection_id'], ['id'], ondelete='CASCADE')
    op.alter_column('recommendation_settings', 'bestseller_method',
               existing_type=postgresql.ENUM('VOLUME', 'VALUE', 'BALANCED', name='bestsellermethod'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('recommendation_settings_connection_id_fkey'), 'recommendation_settings', type_='foreignkey')
    op.create_foreign_key(None, 'recommendation_settings', 'ecommerce_connections', ['connection_id'], ['id'], ondelete='CASCADE')

    # Drop old PG enum types (no longer used — columns are now varchar)
    op.execute("DROP TYPE IF EXISTS platformtype")
    op.execute("DROP TYPE IF EXISTS recommendationtype")
    op.execute("DROP TYPE IF EXISTS eventtype")
    op.execute("DROP TYPE IF EXISTS bestsellermethod")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Re-create PG enum types for downgrade
    op.execute("CREATE TYPE platformtype AS ENUM ('SHOPIFY', 'WOOCOMMERCE', 'MAGENTO')")
    op.execute("CREATE TYPE recommendationtype AS ENUM ('BESTSELLER', 'CROSS_SELL', 'UP_SELL', 'SIMILAR', 'USER_BASED')")
    op.execute("CREATE TYPE eventtype AS ENUM ('VIEW', 'CLICK', 'PURCHASE')")
    op.execute("CREATE TYPE bestsellermethod AS ENUM ('VOLUME', 'VALUE', 'BALANCED')")

    op.drop_constraint(None, 'recommendation_settings', type_='foreignkey')
    op.create_foreign_key(op.f('recommendation_settings_connection_id_fkey'), 'recommendation_settings', 'ecommerce_connections', ['connection_id'], ['id'])
    op.alter_column('recommendation_settings', 'bestseller_method',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('VOLUME', 'VALUE', 'BALANCED', name='bestsellermethod'),
               existing_nullable=False)
    op.drop_constraint(None, 'recommendation_analytics', type_='foreignkey')
    op.create_foreign_key(op.f('recommendation_analytics_connection_id_fkey'), 'recommendation_analytics', 'ecommerce_connections', ['connection_id'], ['id'])
    op.alter_column('recommendation_analytics', 'event_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('VIEW', 'CLICK', 'PURCHASE', name='eventtype'),
               existing_nullable=False)
    op.alter_column('recommendation_analytics', 'recommendation_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('BESTSELLER', 'CROSS_SELL', 'UP_SELL', 'SIMILAR', 'USER_BASED', name='recommendationtype'),
               existing_nullable=False)
    op.drop_constraint(None, 'ecommerce_connections', type_='foreignkey')
    op.drop_constraint(None, 'ecommerce_connections', type_='foreignkey')
    op.create_foreign_key(op.f('ecommerce_connections_organization_id_fkey'), 'ecommerce_connections', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('ecommerce_connections_user_id_fkey'), 'ecommerce_connections', 'users', ['user_id'], ['id'])
    op.alter_column('ecommerce_connections', 'db_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ecommerce_connections', 'db_password',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('ecommerce_connections', 'db_user',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ecommerce_connections', 'db_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ecommerce_connections', 'db_host',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ecommerce_connections', 'platform',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('SHOPIFY', 'WOOCOMMERCE', 'MAGENTO', name='platformtype'),
               existing_nullable=False)
    op.drop_column('ecommerce_connections', 'api_secret')
    op.drop_column('ecommerce_connections', 'api_key')
    op.drop_column('ecommerce_connections', 'store_url')
    op.drop_column('ecommerce_connections', 'connection_method')
    op.drop_constraint(None, 'api_usage_tracking', type_='foreignkey')
    op.drop_constraint(None, 'api_usage_tracking', type_='foreignkey')
    op.create_foreign_key(op.f('api_usage_tracking_connection_id_fkey'), 'api_usage_tracking', 'ecommerce_connections', ['connection_id'], ['id'])
    op.create_foreign_key(op.f('api_usage_tracking_organization_id_fkey'), 'api_usage_tracking', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
