"""Manual Override

Revision ID: e028859d2bb8
Revises: 9d3e21c823c5
Create Date: 2026-03-02 17:23:02.274514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e028859d2bb8'
down_revision: Union[str, Sequence[str], None] = '9d3e21c823c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('manual_override', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'manual_override')
    # ### end Alembic commands ###
