"""Add BaseMixin fields

Revision ID: a8378bb0f582
Revises: 91d861a1bea9
Create Date: 2026-03-04 14:44:04.584730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8378bb0f582'
down_revision: Union[str, Sequence[str], None] = '91d861a1bea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecommerce_connections', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ecommerce_connections', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('ecommerce_connections', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('ecommerce_connections', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('recommendation_settings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recommendation_settings', sa.Column('deleted_by', sa.Integer(), nullable=True))
    op.add_column('recommendation_settings', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('recommendation_settings', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_settings', 'updated_by')
    op.drop_column('recommendation_settings', 'created_by')
    op.drop_column('recommendation_settings', 'deleted_by')
    op.drop_column('recommendation_settings', 'deleted_at')
    op.drop_column('ecommerce_connections', 'updated_by')
    op.drop_column('ecommerce_connections', 'created_by')
    op.drop_column('ecommerce_connections', 'deleted_by')
    op.drop_column('ecommerce_connections', 'deleted_at')
    # ### end Alembic commands ###
