"""Recommendation Settings Update

Revision ID: 5802f2d03a41
Revises: 85c33b1d507f
Create Date: 2026-03-09 03:45:17.337073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5802f2d03a41'
down_revision: Union[str, Sequence[str], None] = '85c33b1d507f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_settings', sa.Column('widget_style', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('widget_columns', sa.Integer(), nullable=True))
    op.add_column('recommendation_settings', sa.Column('widget_size', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('primary_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('text_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('bg_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('border_radius', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('cta_text', sa.String(length=100), nullable=True))
    op.add_column('recommendation_settings', sa.Column('show_price', sa.Boolean(), nullable=True))
    op.add_column('recommendation_settings', sa.Column('image_aspect', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('widget_title', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation_settings', 'widget_title')
    op.drop_column('recommendation_settings', 'image_aspect')
    op.drop_column('recommendation_settings', 'show_price')
    op.drop_column('recommendation_settings', 'cta_text')
    op.drop_column('recommendation_settings', 'border_radius')
    op.drop_column('recommendation_settings', 'bg_color')
    op.drop_column('recommendation_settings', 'text_color')
    op.drop_column('recommendation_settings', 'primary_color')
    op.drop_column('recommendation_settings', 'widget_size')
    op.drop_column('recommendation_settings', 'widget_columns')
    op.drop_column('recommendation_settings', 'widget_style')
    # ### end Alembic commands ###
