"""AuditLog

Revision ID: 9d3e21c823c5
Revises: a2eb82f6f8db
Create Date: 2026-02-21 03:05:37.897951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d3e21c823c5'
down_revision: Union[str, Sequence[str], None] = 'a2eb82f6f8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nexotype_audit_logs', 'created_at')
    op.drop_column('nexotype_audit_logs', 'deleted_at')
    op.drop_column('nexotype_audit_logs', 'updated_at')
    op.drop_column('nexotype_audit_logs', 'deleted_by')
    op.drop_column('nexotype_audit_logs', 'created_by')
    op.drop_column('nexotype_audit_logs', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nexotype_audit_logs', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('nexotype_audit_logs', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('nexotype_audit_logs', sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('nexotype_audit_logs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('nexotype_audit_logs', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('nexotype_audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
