"""Add ShopifyBilling model

Revision ID: 5a631db3238f
Revises: a8378bb0f582
Create Date: 2026-03-06 04:31:51.392782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a631db3238f'
down_revision: Union[str, Sequence[str], None] = 'a8378bb0f582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopify_billings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('shopify_subscription_gid', sa.String(length=255), nullable=True),
    sa.Column('plan_name', sa.String(length=50), nullable=True),
    sa.Column('billing_status', sa.String(length=50), nullable=False),
    sa.Column('test', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['ecommerce_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id')
    )
    op.create_index(op.f('ix_shopify_billings_id'), 'shopify_billings', ['id'], unique=False)
    op.create_index(op.f('ix_shopify_billings_shopify_subscription_gid'), 'shopify_billings', ['shopify_subscription_gid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopify_billings_shopify_subscription_gid'), table_name='shopify_billings')
    op.drop_index(op.f('ix_shopify_billings_id'), table_name='shopify_billings')
    op.drop_table('shopify_billings')
    # ### end Alembic commands ###
