"""Ingested Models

Revision ID: c81714328def
Revises: 36b104a73b41
Create Date: 2026-03-08 14:10:08.788978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c81714328def'
down_revision: Union[str, Sequence[str], None] = '36b104a73b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('variant_id', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('product_title', sa.String(length=500), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['ecommerce_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'order_id', 'product_id', 'variant_id', name='uq_ingested_order_items_connection_order_product_variant')
    )
    op.create_index(op.f('ix_ingested_order_items_id'), 'ingested_order_items', ['id'], unique=False)
    op.create_table('ingested_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['ecommerce_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'order_id', name='uq_ingested_orders_connection_order')
    )
    op.create_index(op.f('ix_ingested_orders_id'), 'ingested_orders', ['id'], unique=False)
    op.create_table('ingested_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('handle', sa.String(length=500), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('inventory_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('platform_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['ecommerce_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'product_id', name='uq_ingested_products_connection_product')
    )
    op.create_index(op.f('ix_ingested_products_id'), 'ingested_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingested_products_id'), table_name='ingested_products')
    op.drop_table('ingested_products')
    op.drop_index(op.f('ix_ingested_orders_id'), table_name='ingested_orders')
    op.drop_table('ingested_orders')
    op.drop_index(op.f('ix_ingested_order_items_id'), table_name='ingested_order_items')
    op.drop_table('ingested_order_items')
    # ### end Alembic commands ###
