"""Recommendations Settings

Revision ID: b635dae35a96
Revises: 5802f2d03a41
Create Date: 2026-03-09 12:41:48.441959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b635dae35a96'
down_revision: Union[str, Sequence[str], None] = '5802f2d03a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_settings', sa.Column('widget_bg_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('widget_padding', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('title_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('title_size', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('title_alignment', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('gap', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('card_bg_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('card_border_radius', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('card_border_width', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('card_border_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('card_shadow', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('card_padding', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('card_hover', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('image_fit', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('image_radius', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('product_title_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('product_title_size', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('product_title_weight', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('product_title_lines', sa.Integer(), nullable=True))
    op.add_column('recommendation_settings', sa.Column('product_title_alignment', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('price_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('price_size', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('button_text', sa.String(length=100), nullable=True))
    op.add_column('recommendation_settings', sa.Column('button_bg_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('button_text_color', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('button_radius', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('button_size', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('button_variant', sa.String(length=50), nullable=True))
    op.add_column('recommendation_settings', sa.Column('button_full_width', sa.Boolean(), nullable=True))
    op.drop_column('recommendation_settings', 'cta_text')
    op.drop_column('recommendation_settings', 'widget_size')
    op.drop_column('recommendation_settings', 'border_radius')
    op.drop_column('recommendation_settings', 'text_color')
    op.drop_column('recommendation_settings', 'primary_color')
    op.drop_column('recommendation_settings', 'bg_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation_settings', sa.Column('bg_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('recommendation_settings', sa.Column('primary_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('recommendation_settings', sa.Column('text_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('recommendation_settings', sa.Column('border_radius', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('recommendation_settings', sa.Column('widget_size', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('recommendation_settings', sa.Column('cta_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('recommendation_settings', 'button_full_width')
    op.drop_column('recommendation_settings', 'button_variant')
    op.drop_column('recommendation_settings', 'button_size')
    op.drop_column('recommendation_settings', 'button_radius')
    op.drop_column('recommendation_settings', 'button_text_color')
    op.drop_column('recommendation_settings', 'button_bg_color')
    op.drop_column('recommendation_settings', 'button_text')
    op.drop_column('recommendation_settings', 'price_size')
    op.drop_column('recommendation_settings', 'price_color')
    op.drop_column('recommendation_settings', 'product_title_alignment')
    op.drop_column('recommendation_settings', 'product_title_lines')
    op.drop_column('recommendation_settings', 'product_title_weight')
    op.drop_column('recommendation_settings', 'product_title_size')
    op.drop_column('recommendation_settings', 'product_title_color')
    op.drop_column('recommendation_settings', 'image_radius')
    op.drop_column('recommendation_settings', 'image_fit')
    op.drop_column('recommendation_settings', 'card_hover')
    op.drop_column('recommendation_settings', 'card_padding')
    op.drop_column('recommendation_settings', 'card_shadow')
    op.drop_column('recommendation_settings', 'card_border_color')
    op.drop_column('recommendation_settings', 'card_border_width')
    op.drop_column('recommendation_settings', 'card_border_radius')
    op.drop_column('recommendation_settings', 'card_bg_color')
    op.drop_column('recommendation_settings', 'gap')
    op.drop_column('recommendation_settings', 'title_alignment')
    op.drop_column('recommendation_settings', 'title_size')
    op.drop_column('recommendation_settings', 'title_color')
    op.drop_column('recommendation_settings', 'widget_padding')
    op.drop_column('recommendation_settings', 'widget_bg_color')
    # ### end Alembic commands ###
