# Generated by Django 5.2.1 on 2025-08-17 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('biomarker_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('omim_id', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('disease_class', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ensembl_id', models.CharField(db_index=True, max_length=100)),
                ('chromosome', models.CharField(max_length=10)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('species', models.CharField(default='Homo sapiens', max_length=100)),
                ('gene_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IsPartOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peptide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('sequence', models.CharField(max_length=1024, unique=True)),
                ('length', models.IntegerField()),
                ('molecular_weight', models.FloatField()),
                ('isoelectric_point', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_activities', models.JSONField(default=list)),
                ('synthesis_difficulty', models.IntegerField()),
                ('stability_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('treatment_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssociatedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.disease')),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.gene')),
            ],
        ),
        migrations.CreateModel(
            name='Encodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.gene')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='genes',
            field=models.ManyToManyField(related_name='diseases', through='nexotype.AssociatedWith', to='nexotype.gene'),
        ),
        migrations.CreateModel(
            name='GeneParticipatesIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.gene')),
            ],
        ),
        migrations.CreateModel(
            name='Indicates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biomarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.biomarker')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.disease')),
            ],
        ),
        migrations.AddField(
            model_name='biomarker',
            name='diseases',
            field=models.ManyToManyField(related_name='biomarkers', through='nexotype.Indicates', to='nexotype.disease'),
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kegg_id', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('pathway_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genes', models.ManyToManyField(related_name='pathways', through='nexotype.GeneParticipatesIn', to='nexotype.gene')),
                ('parent_pathways', models.ManyToManyField(related_name='child_pathways', through='nexotype.IsPartOf', to='nexotype.pathway')),
            ],
        ),
        migrations.AddField(
            model_name='ispartof',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_child_of', to='nexotype.pathway'),
        ),
        migrations.AddField(
            model_name='ispartof',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_parent_of', to='nexotype.pathway'),
        ),
        migrations.AddField(
            model_name='geneparticipatesin',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.pathway'),
        ),
        migrations.CreateModel(
            name='HasActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bio_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.bioactivity')),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.peptide')),
            ],
        ),
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('peptide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.peptide')),
            ],
        ),
        migrations.AddField(
            model_name='bioactivity',
            name='peptides',
            field=models.ManyToManyField(related_name='activities', through='nexotype.HasActivity', to='nexotype.peptide'),
        ),
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.phenotype')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('uniprot_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.TextField()),
                ('molecular_weight', models.FloatField()),
                ('isoelectric_point', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genes', models.ManyToManyField(related_name='proteins', through='nexotype.Encodes', to='nexotype.gene')),
            ],
        ),
        migrations.AddField(
            model_name='peptide',
            name='proteins',
            field=models.ManyToManyField(related_name='peptides', through='nexotype.Contains', to='nexotype.protein'),
        ),
        migrations.CreateModel(
            name='InteractsWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_strength', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacts_out', to='nexotype.protein')),
                ('target_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacts_in', to='nexotype.protein')),
            ],
        ),
        migrations.CreateModel(
            name='HasDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.protein')),
            ],
        ),
        migrations.AddField(
            model_name='encodes',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.protein'),
        ),
        migrations.AddField(
            model_name='contains',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.protein'),
        ),
        migrations.CreateModel(
            name='ProteinDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('pfam_id', models.CharField(db_index=True, max_length=100)),
                ('proteins', models.ManyToManyField(related_name='domains', through='nexotype.HasDomain', to='nexotype.protein')),
            ],
        ),
        migrations.AddField(
            model_name='hasdomain',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.proteindomain'),
        ),
        migrations.CreateModel(
            name='ProteinParticipatesIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.pathway')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.protein')),
            ],
        ),
        migrations.AddField(
            model_name='pathway',
            name='proteins',
            field=models.ManyToManyField(related_name='pathways', through='nexotype.ProteinParticipatesIn', to='nexotype.protein'),
        ),
        migrations.CreateModel(
            name='Treats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.disease')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.treatment')),
            ],
        ),
        migrations.AddField(
            model_name='treatment',
            name='diseases',
            field=models.ManyToManyField(related_name='treatments', through='nexotype.Treats', to='nexotype.disease'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rs_id', models.CharField(db_index=True, max_length=100)),
                ('chromosome', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('reference_allele', models.CharField(max_length=10)),
                ('alternate_allele', models.CharField(max_length=10)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='nexotype.gene')),
                ('phenotypes', models.ManyToManyField(related_name='variants', through='nexotype.Causes', to='nexotype.phenotype')),
            ],
        ),
        migrations.AddField(
            model_name='causes',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexotype.variant'),
        ),
    ]
